### ISSUE TITLE
关于代码运行问题

### ISSUE THREAD

**Issue by AArutoria** [gfmei/ogmm#1]
您好，感谢您对这篇论文和代码的贡献，最近在运行您的代码的时候遇到了一些问题想向您请教下。首先是配置参数问题，我将cfgs.py中的model改为GMMReg才可以运行的，那么源代码中的CluReg是什么含义呢？第二个为代码运行到gmmreg.py中的GMMReg后依然有问题，提示在76行（但我看第76行是被注释掉了），报错内容为：

  File "/media/ogmm-main/ogmm-main/models/gmmreg.py", line 76, in forward
    src_clu_loss = self.cluloss(src, src_xyz_mu, src_feats, src_gamma)[1]
IndexError: index 1 is out of bounds for dimension 0 with size 0

我尝试过Debug，但点云经过DGCNN提取特征后的一些代码就会出问题，我实在是不清楚问题出在哪里了........

如果您看到了，可以解答我的疑惑嘛，再次谢谢您。

**Comment by gfmei** [comment]
抱歉，我代码还没更新完

**Comment by gfmei** [comment]
您好，感谢您对本工作的关注，这是一个draft版本，我代码还没更新完，我这个月会更新完的。

**Comment by AArutoria** [comment]
> 您好，感谢您对本工作的关注，这是一个draft版本，我代码还没更新完，我这个月会更新完的。

好的  再次谢谢您  祝您工作顺利 生活愉快

**Comment by AArutoria** [comment]
您好，感谢您这段时间一直在更新代码，它已经可以跑了。但我还是遇到了问题：在测试时，您在gmmreg的最后写了一个is_test判断语句 内容为：reg_solver( )其作用是使用ICP算法求解变换矩阵吗？？？  这样的目的是什么呢？？？ 还有就是代码运行reg_solver()里中的 o3d.pipelines.registration.registration_icp（）时报错了  提示 AttributeError：module open3d has no attribute ‘pipelines’   是我虚拟环境中的open3d版本问题吗？还是其他的问题？

请问您可以帮我答疑解惑嘛  谢谢您

**Comment by gfmei** [comment]
icp是fine-tune一下，你也可以去掉这个，AttributeError：module open3d has no attribute ‘pipelines’是版本问题。

**Comment by AArutoria** [comment]
> icp是fine-tune一下，你也可以去掉这个，AttributeError：module open3d has no attribute ‘pipelines’是版本问题。

嗷嗷好的。还有最后一个问题 请问您遇到梯度爆炸的问题了嘛 训练验证过程中输出的loss 或者是 RMSE等指标 输出为nan

**Comment by gfmei** [comment]
> > icp是fine-tune一下，你也可以去掉这个，AttributeError：module open3d has no attribute ‘pipelines’是版本问题。
> 
> 嗷嗷好的。还有最后一个问题 请问您遇到梯度爆炸的问题了嘛 训练验证过程中输出的loss 或者是 RMSE等指标 

我有遇到过，dcp_loss 前面的系数设置为1就可以了。

**Comment by Shi-Qi-Li** [comment]
> 

您好，我想咨询一下dcp_loss前面的系数设置为1具体是在哪里设置呀？

**Comment by Shi-Qi-Li** [comment]
> > > icp是fine-tune一下，你也可以去掉这个，AttributeError：module open3d has no attribute ‘pipelines’是版本问题。
> > 
> > 
> > 嗷嗷好的。还有最后一个问题 请问您遇到梯度爆炸的问题了嘛 训练验证过程中输出的loss 或者是 RMSE等指标
> 
> 我有遇到过，dcp_loss 前面的系数设置为1就可以了。

您好，我想咨询一下dcp_loss前面的系数设置为1具体是在哪里设置呀？
