### ISSUE TITLE
About 7Scene dataset

### ISSUE THREAD

**Issue by username-kiki** [gfmei/ogmm#2]
How do I download the 7scene dataset in ply format? It's been bothering me for a long time. Looking forward to your reply :)

**Comment by username-kiki** [comment]
I also don't know how to download the ICL-NUIM dataset. If possible, sincerely hope you can provide Baidu Cloud link. I'm really interested in your work. Thank you.

**Comment by gfmei** [comment]
> I also don't know how to download the ICL-NUIM dataset. If possible, sincerely hope you can provide Baidu Cloud link. I'm really interested in your work. Thank you.



> How do I download the 7scene dataset in ply format? It's been bothering me for a long time. Looking forward to your reply :)

https://drive.google.com/file/d/1XdQ3muo5anFA28ZFch06z_iTEjXxLEQi/view

**Comment by gfmei** [comment]
> How do I download the 7scene dataset in ply format? It's been bothering me for a long time. Looking forward to your reply :)

https://drive.google.com/file/d/1XdQ3muo5anFA28ZFch06z_iTEjXxLEQi/view

**Comment by gfmei** [comment]
> 

For icl_nuim, you can following deepgmr.

**Comment by gfmei** [comment]
> > I also don't know how to download the ICL-NUIM dataset. If possible, sincerely hope you can provide Baidu Cloud link. I'm really interested in your work. Thank you.

You can follow deepgmr.
> 
> > How do I download the 7scene dataset in ply format? It's been bothering me for a long time. Looking forward to your reply :)
> 
> https://drive.google.com/file/d/1XdQ3muo5anFA28ZFch06z_iTEjXxLEQi/view

**Comment by username-kiki** [comment]
Thank you for your patient answer. The problem has been solved.
