### ISSUE TITLE
About Overlap score prediction

### ISSUE THREAD

**Issue by Ruye-aa** [gfmei/ogmm#3]
Thanks for your great work !
I'm interested in the overlap score prediction block in your paper, I notice that the score is calculated by combining softmax, instance regularization and sigmoid before linear layer. Have you tried just passing the features through a linear layer to get the final score？Is there a noticeable gap between the two? Or have you tried other ways to calculate the overlap score?
Thanks a lot !

**Comment by gfmei** [comment]
Thank you for your interest in our work. We do not try other networks.
