### ISSUE TITLE
模型训练结果

### ISSUE THREAD

**Issue by sam-zyzhang** [gfmei/ogmm#4]
感谢您在这个工作上的贡献！
我训练过程中，并没有改动任何模型参数，仅仅将cfgs.py文件中的--model改为GMMReg，在ModelNet40的数据集上的训练过程在经过前两个epoch之后并不会提高了，验证时的recall保持在0.2370，且后续并没有任何改善。我的GPU是3090，batch_size设置为48。能否提供训练好的模型以便测试和学习？谢谢

**Comment by gfmei** [comment]
不应该啊，我过段时间会提供的

**Comment by liyuan123-1** [comment]
你好，非常感谢您杰出的工作，我也遇到了相同的情况，我采用代码中所设置的参数，但是当我训练到第170个epoch以后recall一直保持在0.5790，我的机器是3090.，能否提供训练好的模型以便测试嘛。非常感谢。
